### ISSUE TITLE
[input_as_map] Can't send null for slice inputs

### ISSUE THREAD

**Issue by DENKweit** [infiotinc/gqlgenc#14]
Schema:
```
input FooInput {
   ids: [String!]
}
```
Generates:
```golang
func WithIDs(v []string) { ... }
```
I think that instead this should be generated so a list is also nullable:
```golang
func WithIDs(v *[]string) { ... }
```

**Comment by raphaelfff** [comment]
I added a test for that, you can pass `nil` for `[]string`

https://github.com/infiotinc/gqlgenc/compare/issue-14

This seem to exhibit the correct behavior, can you confirm ?

**Comment by DENKweit** [comment]
Indeed, it works. Sorry for the fuss!
